# TinyContainer
#
#  Copyright (C) 2023-2024 Orange
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.


#tinycontainer modules includes all required submodules
ifneq (,$(filter tinycontainer,$(USEMODULE)))
  USEMODULE += tinycontainer_service
  USEMODULE += tinycontainer_runtime
  ifneq (,$(filter jerryscript,$(TINYCONTAINER_RUNTIME)))
    USEMODULE += tinycontainer_runtime_jerryscript
  endif
  ifneq (,$(filter wamr,$(TINYCONTAINER_RUNTIME)))
    USEMODULE += tinycontainer_runtime_wamr
  endif
  ifneq (,$(filter rbpf,$(TINYCONTAINER_RUNTIME)))
    USEMODULE += tinycontainer_runtime_rbpf
  endif
  USEMODULE += tinycontainer_controller
  USEMODULE += tinycontainer_security
  USEMODULE += tinycontainer_memmgr
  ifneq (,$(filter ram,$(TINYCONTAINER_MEMMGR)))
    USEMODULE += tinycontainer_memmgr_ram
  endif
  USEMODULE += tinycontainer_security_crypto
  ifneq (,$(filter none,$(TINYCONTAINER_CRYPTO)))
    USEMODULE += tinycontainer_security_crypto_none
  endif
  ifneq (,$(filter psa,$(TINYCONTAINER_CRYPTO)))
    USEMODULE += tinycontainer_security_crypto_psa
  endif
endif

#submodules dependencies

ifneq (,$(filter tinycontainer_service,$(USEMODULE)))
  USEMODULE += tinycontainer
  USEMODULE += tinycontainer_security_sthread
  USEMODULE += tinycontainer_security_cwt
  USEMODULE += tinycontainer_runtime
  USEMODULE += tinycontainer_metadata
endif

ifneq (,$(filter tinycontainer_runtime,$(USEMODULE)))
  USEMODULE += tinycontainer_security_sthread
  USEMODULE += ztimer
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter tinycontainer_memmgr,$(USEMODULE)))
  USEMODULE += tinycontainer_security_sthread
  USEMODULE += tinycontainer_metadata
endif

ifneq (,$(filter tinycontainer_security_cwt,$(USEMODULE)))
  USEPKG += nanocbor
endif

ifneq (,$(filter tinycontainer_metadata,$(USEMODULE)))
  USEPKG += nanocbor
  USEMODULE += tinycontainer_security_crypto
endif

ifneq (,$(filter tinycontainer_runtime_wamr,$(USEMODULE)))
  USEMODULE += tinycontainer
  USEMODULE += tinycontainer_runtime
  USEMODULE += tinycontainer_memmgr
  USEPKG += wamr
endif
ifneq (,$(filter tinycontainer_runtime_jerryscript,$(USEMODULE)))
  USEMODULE += tinycontainer_runtime
  USEMODULE += tinycontainer_memmgr
  USEPKG += jerryscript
endif
ifneq (,$(filter tinycontainer_runtime_rbpf,$(USEMODULE)))
  USEMODULE += tinycontainer_runtime
  USEMODULE += tinycontainer_memmgr
  USEMODULE += rbpf
endif
