# TinyContainer
#
#  Copyright (C) 2023 Orange
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.


#tinycontainer modules includes all required submodules
ifneq (,$(filter tinycontainer,$(USEMODULE)))
  USEMODULE += tinycontainer_service
  USEMODULE += tinycontainer_container
  ifneq (,$(filter jerryscript,$(TINYCONTAINER_CONTAINER)))
    USEMODULE += tinycontainer_container_jerryscript
  endif
  ifneq (,$(filter wamr,$(TINYCONTAINER_CONTAINER)))
    USEMODULE += tinycontainer_container_wamr
  endif
  ifneq (,$(filter rbpf,$(TINYCONTAINER_CONTAINER)))
    USEMODULE += tinycontainer_container_rbpf
  endif
  USEMODULE += tinycontainer_controller
  USEMODULE += tinycontainer_firewall
  USEMODULE += tinycontainer_memmgr
  ifneq (,$(filter ram,$(TINYCONTAINER_MEMMGR)))
    USEMODULE += tinycontainer_memmgr_ram
  endif
endif

#submodules dependencies

ifneq (,$(filter tinycontainer_service,$(USEMODULE)))
  USEMODULE += tinycontainer
  USEMODULE += tinycontainer_firewall
  USEMODULE += tinycontainer_container
endif

ifneq (,$(filter tinycontainer_container,$(USEMODULE)))
  USEMODULE += ztimer
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter tinycontainer_container_wamr,$(USEMODULE)))
  USEMODULE += tinycontainer
  USEMODULE += tinycontainer_container
  USEMODULE += tinycontainer_memmgr
  USEPKG += wamr
endif
ifneq (,$(filter tinycontainer_container_jerryscript,$(USEMODULE)))
  USEMODULE += tinycontainer_container
  USEMODULE += tinycontainer_memmgr
  USEPKG += jerryscript
endif
ifneq (,$(filter tinycontainer_container_rbpf,$(USEMODULE)))
  USEMODULE += tinycontainer_container
  USEMODULE += tinycontainer_memmgr
  USEMODULE += rbpf
endif
