# TinyContainer
#
#  Copyright (C) 2024 Orange
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.

wamr:
	@$(MAKE) -f Makefile.wamr

rbpf:
	@$(MAKE) -f Makefile.rbpf

jerryscript:
	@$(MAKE) -f Makefile.jerryscript
